name: deploy

on:
  push:
    branches: [main]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Dockerhub login
      env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
          buildx-version: latest

    # - name: Build base image with push
    #   run: |
    #       docker buildx build \
    #       --platform=linux/amd64 \
    #       --output "type=image,push=true" \
    #       --file ./Dockerfile . \
    #       --tag jhonoryza/frankenphp-pgsql:8.2

    - name: Build dockerfile (with push)
      run: |
          docker buildx build \
          --platform=linux/amd64 \
          --output "type=image,push=true" \
          --file ./production.Dockerfile . \
          --tag jhonoryza/learningtodo:latest

  deploy:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Connect and run command on remote server
      uses: and-fm/cloudflared-ssh-action@v3
      with:
        host: dell.labkita.my.id
        username: root
        private_key_filename: id_rsa
        private_key_value: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        service_token_id: ${{ secrets.CLIENT_ID }}
        service_token_secret: ${{ secrets.CLIENT_SECRET }}
        commands: /media/server_data/docker/laravel-projects/deploy-learningtodo.sh
